### ISSUE TITLE
Rplidar does not support A1M8-R6 firmware version

### ISSUE THREAD

**Issue by TCIII** [adafruit/Adafruit_CircuitPython_RPLIDAR#20]
SBC: Rpi 3B+
OS: Latest Buster Desktop

I have both a Slamtec A1M8-R5 and a A1M8-R6 which is the latest hardware and firmware (v 1.29)

When I run ["display_lidar_pi"](https://learn.adafruit.com/slamtec-rplidar-on-pi/cpython-on-raspberry-pi) using my A1M8-R5, I get the expected Lidar display on my LCD display.

When I run "display_lidar_pi.py" using my A1M8-R6, I get the following error message: "adafruit_rplidar .rplidar exception: wrong body size"

I have searched the IoT for a possible solution to the "adafruit_rplidar .rplidar exception: wrong body size" error, but have experienced no joy.

The A1M8-R5 is two years old and is running an early version of the A1M8 firmware. The A1M8-R6 is running the latest firmware.

Obviously the Adafruit RPLidar module is taking an exception to the latest A1M8-R6 firmware, but has no issue with the A1M8-R5 firmware.

I am using the Adafruit RPLidar module with both the A1M8-R5 and R6 on my Donkey Car platform and have no issues connecting with either A1M8 and collecting data.

Is there a line of code in the "display_lidar_pi.py" program that can be adjusted to overcome the dreaded "adafruit_rplidar .rplidar exception: wrong body size" error?

Here is the complete error message when using the A1M8-R6:

pygame 1.9.4.post1
Hello from the pygame community. https://www.pygame.org/contribute.html
{'model': 24, 'firmware': (1, 29), 'hardware': 7, 'serialnumber': '14342370f79ce5c5d49ae5c9f699f18c'}
Traceback (most recent call last):
File "display_lidar_pi.py", line 55, in <module>
for scan in lidar.iter_scans():
File "/home/pi/.local/lib/python3.7/site-packages/adafruit_rplidar.py", line 508, in iter_scans
for new_scan, quality, angle, distance in iterator:
File "/home/pi/.local/lib/python3.7/site-packages/adafruit_rplidar.py", line 433, in iter_measurements
raw = self._read_response(dsize)
File "/home/pi/.local/lib/python3.7/site-packages/adafruit_rplidar.py", line 261, in _read_response
raise RPLidarException("Wrong body size")
adafruit_rplidar.RPLidarException: Wrong body size

**Comment by TCIII** [comment]
Update:

I have found that if I run the "Usage Example" Python program I can get the RPLidar range data displayed as sequential millimeter readings on my LCD display for both the A1M8-R5 and the A1M8-R6, but still cannot display the A1M8-R6 range data as dots scaled to fit my LCD display as I can with the A1M8-R5 when running ["display_lidar_pi.py".](https://learn.adafruit.com/slamtec-rplidar-on-pi/cpython-on-raspberry-pi)

There is obviously an issue with "display_lidar_pi.py" that is occurring with the A1M8-R6 that is not occurring with the A1M8-R5 which will display the range data as dots scaled to fit my LCD display.

**Comment by TCIII** [comment]
I figured out the issue: There is a missing "timeout" value in the Adafruit "display_lidar_pi.py" Python program.
